# SAM configuration file for AcademiaSearch Lambda
version = 0.1

[default.global.parameters]
stack_name = "academia-search-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=prod"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "academia-search-stack"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=prod"
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"